#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""
Generates tf_rom_fold.v — the psi-fold twiddle ROM (512 stored words instead
of 1023) — MECHANICALLY from the reference tf_ROM.v, so no table is ever
hand-transcribed.

Stored contents are the 9^-1-scaled lower half of the w_rom table (composing
with the CFNTT-KRED butterfly, which expects W = 9^-1*w); the upper half is
derived on the fly by fold7 (7x mod q as (x<<3)-x + three conditional
subtractions — psi = kesai = 7, and w_rom[512+j] = 7*w_rom[j] by the
bit-reversed layout).  See rom_fold_math.py for the proofs.
"""

import os
import re

Q = 12289
INV9 = pow(9, -1, Q)
HERE = os.path.dirname(os.path.abspath(__file__))

rom_v = open(os.path.join(HERE, "..", "..", "cfntt_ref",
                          "hardware_code_radix-2", "tf_ROM.v")).read()
entries = {int(a): int(v) for a, v in
           re.findall(r"10'd(\d+):\s*Q\s*<=\s*14'd(\d+);", rom_v)}
assert sorted(entries) == list(range(1023))
W = [1] + [entries[a] for a in range(1023)]          # w_rom[0..1023]
assert all(W[512 + j] == (7 * W[j]) % Q for j in range(512))

ROM512 = [(INV9 * W[j]) % Q for j in range(512)]     # the ONLY stored words

cases = "\n".join("      9'd%d: base <= 14'd%d;" % (j, v)
                  for j, v in enumerate(ROM512))

open(os.path.join(HERE, "tf_rom_fold.v"), "w").write(f"""\
// GENERATED by gen_rom_fold.py from cfntt_ref/hardware_code_radix-2/tf_ROM.v
// — do not edit by hand; regenerate instead.
//
// The psi-fold twiddle ROM: same interface and 1-cycle latency as tf_ROM.v,
// half the stored bits.  The bit-reversed negacyclic layout satisfies
// w_rom[512+j] == 7*w_rom[j] (mod q)  [psi = kesai = 7], so only w_rom[0..511]
// (9^-1-scaled for the CFNTT-KRED butterfly) is stored; addresses covering
// the upper half derive their word with fold7: 7x = (x<<3)-x reduced by
// three conditional subtractions — shifts and adds only, no multiplier.
//
// Address semantics match tf_ROM.v: A in [0,1023) selects w_rom[A+1].
module tf_rom_fold
    #(parameter addr_rom_width = 10,
                 data_width = 14)
    (
    input clk,
    input [addr_rom_width-1:0] A,
    input REN,
    output wire [data_width-1:0] Q
    );

    parameter q = 14'd12289;

    wire [9:0] i = A + 10'd1;          // w_rom index 1..1023
    reg  [13:0] base;
    reg         upper;

    always @(posedge clk) begin
      if (REN == 1'b1) begin
        upper <= i[9];
        case (i[8:0])
{cases}
        endcase
      end
    end

    // fold7: 7*base mod q, exact for base < q (z3-proven in verify_rom_fold.py).
    // Parallel reduction (shallow critical path): 7x is in [0,7q), so
    // m = floor(7x/q) in 0..6 is picked by six CONSTANT comparators in
    // parallel, then a SINGLE subtraction m*q -- instead of three chained
    // conditional subtracts.  Cuts the derived-half combinational depth.
    wire [16:0] t = {{base, 3'b000}} - {{3'd0, base}};        // 7x < 7q < 2^17
    // mq = m*q selected from PRECOMPUTED constants (a 7-way mux, pure LUT --
    // no multiplier), so the fold stays DSP-free.
    wire [16:0] mq = (t >= 17'd73734) ? 17'd73734 :          // 6q
                     (t >= 17'd61445) ? 17'd61445 :          // 5q
                     (t >= 17'd49156) ? 17'd49156 :          // 4q
                     (t >= 17'd36867) ? 17'd36867 :          // 3q
                     (t >= 17'd24578) ? 17'd24578 :          // 2q
                     (t >= 17'd12289) ? 17'd12289 : 17'd0;   //  q
    wire [16:0] r  = t - mq;                                  // single subtract, < q

    assign Q = upper ? r[13:0] : base;
endmodule
""")
print("tf_rom_fold.v generated: 512 stored words (9^-1-scaled)")
