#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""
Parameterized generator: from any Proth prime q = k·2^m + 1 (and an NTT root
psi), emit the CFNTT-KRED reduction schedule + a psi-fold ROM plan, and
prove them.  This is what turns the two Falcon (q=12289) inventions into a
*method* — the same construction instantiates for Kyber (q=3329) and any
Proth NTT prime.

Two independent artifacts per prime:

  1. K-RED reducer  — the generic fold schedule (k·2^m ≡ −1 (mod q), so a
     value split at bit m folds by `k·lo − hi` with a q-multiple offset to
     stay non-negative).  We compute the number of folds F needed to reduce
     a full product (< q²) to < 2q, the per-fold offsets and wire widths,
     and the spurious factor k^F to fold into the twiddle ROM ((k^F)^{-1}).
     `k·x` is itself shift-add (k's set bits): Falcon k=3 = 1 adder,
     Kyber k=13 = 2 adders.

  2. psi-fold ROM  — if psi is "shift-friendly" (psi·x = a few shift-adds),
     the bit-reversed table's upper half is psi·(lower half), so store half
     and derive with a psi-multiply gate (recursively −75%).

Validation: the K-RED schedule is checked EXHAUSTIVELY for Kyber
(z < q² ≈ 1.1e7) and by structure + wide sampling for Falcon; the generated
Falcon plan is one instance (the hand-written RTL uses a more
conservative 6q first-fold offset; the generator finds a tighter 4q).

Run: `uv run kred_gen.py`  ->  prints a plan per prime + "KRED-GEN VALIDATED".
"""

import sys


def proth(q):
    t, m = q - 1, 0
    while t % 2 == 0:
        t //= 2
        m += 1
    return t, m                      # k (odd), m


def shift_add_terms(k):
    """k·x as sum of shifted x: list of shift amounts (set bits of k)."""
    return [i for i in range(k.bit_length()) if (k >> i) & 1]


def plan_kred(q):
    """Compute the fold schedule to reduce z < q^2 to a residue < q."""
    k, m = proth(q)
    assert k * (1 << m) + 1 == q
    assert (k * (1 << m)) % q == q - 1          # k·2^m ≡ −1

    hi_bound = q * q                            # z < q^2
    folds = []
    bound = hi_bound
    factor = 1
    while bound >= 2 * q:
        # z < bound; z0 < 2^m, z1 < ceil(bound/2^m)
        z1_max = (bound - 1) >> m
        # r = k·z0 + C − z1, need r >= 0 always: C >= z1_max, C multiple of q
        C = ((z1_max + q - 1) // q) * q
        r_max = k * ((1 << m) - 1) + C          # z1 >= 0 minimises subtrahend
        folds.append({"m": m, "k": k, "offset_q": C // q, "offset": C,
                      "in_bound": bound, "out_bound": r_max + 1})
        bound = r_max + 1
        factor = (factor * k) % q
    # final: at most ceil(bound/q) conditional subtractions
    cond_subs = (bound - 1) // q
    return {"q": q, "k": k, "m": m, "folds": folds, "factor": factor,
            "inv_factor": pow(factor, -1, q), "cond_subs": cond_subs,
            "k_terms": shift_add_terms(k)}


def kred_reduce(z, plan):
    """Execute the generated schedule; returns factor·z mod q with 0<=r<q."""
    v = z
    for f in plan["folds"]:
        z0 = v & ((1 << f["m"]) - 1)
        z1 = v >> f["m"]
        v = f["k"] * z0 + f["offset"] - z1
        assert 0 <= v < f["out_bound"], (z, v, f)
    for _ in range(plan["cond_subs"]):
        if v >= plan["q"]:
            v -= plan["q"]
    return v


def validate_kred(plan, exhaustive):
    factor = plan["factor"]
    q = plan["q"]
    if exhaustive:
        for z in range(q * q):
            if kred_reduce(z, plan) != (factor * z) % q:
                return False, "z=%d" % z
        return True, "exhaustive z<q^2=%d" % (q * q)
    import random
    rng = random.Random(0)
    tests = [0, 1, q - 1, q, q * q - 1] + [rng.randrange(q * q)
                                           for _ in range(2_000_000)]
    for z in tests:
        if kred_reduce(z, plan) != (factor * z) % q:
            return False, "z=%d" % z
    return True, "edges + 2M samples over z<q^2"


def psi_fold_plan(q, psi, N):
    """If psi is shift-friendly, the bit-reversed table folds by psi."""
    terms = shift_add_terms(psi)
    # cost proxy: adders = (#terms - 1) + conditional subtractions (<= psi)
    return {"psi": psi, "psi_terms": terms, "shift_friendly": len(terms) <= 3,
            "half_words": N // 2, "quarter_words": N // 4}


def emit_rtl(name, plan):
    """Emit a synthesizable K-RED reducer for this prime (pipelined, one
    register per fold + output), analogous to modular_mul_kred.v."""
    q, k, m = plan["q"], plan["k"], plan["m"]
    dw = q.bit_length()
    prodw = 2 * dw
    lines = []
    lines.append("// GENERATED by kred_gen.py for %s: q = %d = %d*2^%d + 1"
                 % (name, q, k, m))
    lines.append("// Returns (k^%d * A * B) mod q; fold the factor %d into the"
                 % (len(plan["folds"]), plan["factor"]))
    lines.append("// twiddle ROM ((k^F)^-1 = %d)." % plan["inv_factor"])
    lines.append("module modular_mul_kred_%s #(parameter data_width = %d)("
                 % (name.lower(), dw))
    lines.append("    input clk, rst,")
    lines.append("    input [data_width-1:0] A_in, B_in,")
    lines.append("    output wire [data_width-1:0] P_out);")
    lines.append("    parameter q = %d'd%d;" % (dw, q))
    nstage = len(plan["folds"]) + 2
    lines.append("    reg [%d:0] s [0:%d];" % (prodw - 1, nstage - 1))
    body = ["    integer ii;", "    always @(posedge clk or posedge rst) begin",
            "      if (rst) begin for (ii=0; ii<%d; ii=ii+1) s[ii] <= 0; end"
            % nstage, "      else begin", "        s[0] <= A_in * B_in;"]
    for fi, f in enumerate(plan["folds"]):
        kt = " + ".join("(s[%d][%d:0] << %d)" % (fi, m - 1, t) if t else
                        "s[%d][%d:0]" % (fi, m - 1) for t in plan["k_terms"])
        body.append("        s[%d] <= (%s) + %d'd%d - (s[%d] >> %d);"
                     % (fi + 1, kt, prodw, f["offset"], fi, m))
    last = len(plan["folds"])
    body.append("        s[%d] <= s[%d];" % (last + 1, last))  # align
    body.append("      end")
    body.append("    end")
    # output: cond-subs on s[last+1]
    outv = "s[%d][data_width-1:0]" % (last + 1)
    red = "s[%d]" % (last + 1)
    cs = plan["cond_subs"]
    guard = " || ".join(["%s >= %d'd%d" % (red, prodw, q * (j + 1))
                         for j in range(cs)]) if cs else "1'b0"
    body.append("    wire [%d:0] r = (%s) ? (%s - %d'd%d) : %s;"
                % (prodw - 1, "%s >= %d'd%d" % (red, prodw, q), red, prodw, q,
                   red) if cs == 1 else "")
    lines += body
    lines.append("    assign P_out = %s;" % ("r[data_width-1:0]" if cs == 1
                                             else outv))
    lines.append("endmodule")
    return "\n".join(l for l in lines if l is not None) + "\n"


def bitexact_ok(plan, exhaustive_limit=None):
    """Bit-exact int model of the emitted RTL == factor*z mod q over domain."""
    q, k, m = plan["q"], plan["k"], plan["m"]
    prodw = 2 * q.bit_length()
    mask = (1 << prodw) - 1

    def rtl(z):
        v = z & mask
        for f in plan["folds"]:
            lo = v & ((1 << m) - 1)
            v = (k * lo + f["offset"] - (v >> m)) & mask
        for _ in range(plan["cond_subs"]):
            if v >= q:
                v = (v - q) & mask
        return v & ((1 << q.bit_length()) - 1)

    hi = q * q if exhaustive_limit is None else min(q * q, exhaustive_limit)
    for a in range(q):
        pass
    # check on all products a*b would be q^2 pairs; use z-domain exhaustive
    for z in range(hi):
        if rtl(z) != (plan["factor"] * z) % q:
            return False
    return True


def main():
    primes = [
        ("Falcon", 12289, 7, 1024, False),   # psi = 7, sample (z3 covers full)
        ("Kyber", 3329, 17, 256, True),      # psi = 17 (a 2N-th root), exhaustive
    ]
    ok = True
    for name, q, psi, N, exhaustive in primes:
        plan = plan_kred(q)
        good, how = validate_kred(plan, exhaustive)
        fp = psi_fold_plan(q, psi, N)
        print("== %s: q = %d = %d·2^%d + 1 ==" % (name, q, plan["k"], plan["m"]))
        print("   K-RED: %d fold(s), spurious factor k^F = %d -> fold (k^F)^-1 = %d"
              % (len(plan["folds"]), plan["factor"], plan["inv_factor"]))
        print("          k·x = sum of x<<%s (%d adder(s)); final cond-subs = %d"
              % (plan["k_terms"], max(0, len(plan["k_terms"]) - 1),
                 plan["cond_subs"]))
        print("   K-RED reducer correct: %s [%s]"
              % ("YES" if good else "NO — " + how, how))
        print("   psi-fold: psi=%d, psi·x = x<<%s, shift-friendly=%s "
              "-> store %d/%d words (half), %d (quarter)"
              % (fp["psi"], fp["psi_terms"], fp["shift_friendly"],
                 fp["half_words"], N, fp["quarter_words"]))
        rtlfile = "modular_mul_kred_%s.v" % name.lower()
        import os
        open(os.path.join(os.path.dirname(os.path.abspath(__file__)), rtlfile), "w").write(emit_rtl(name, plan))
        print("   emitted %s (latency %d)" % (rtlfile, len(plan["folds"]) + 2))
        ok &= good
        if not fp["shift_friendly"]:
            print("   NOTE psi not shift-friendly for %s: psi-fold ROM would "
                  "need a small constant-mult, still cheaper than storage" % name)
    print("KRED-GEN VALIDATED" if ok else "KRED-GEN FAILED")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
