// GENERATED by kred_gen.py for Falcon: q = 12289 = 3*2^12 + 1
// Returns (k^2 * A * B) mod q; fold the factor 9 into the
// twiddle ROM ((k^F)^-1 = 2731).
module modular_mul_kred_falcon #(parameter data_width = 14)(
    input clk, rst,
    input [data_width-1:0] A_in, B_in,
    output wire [data_width-1:0] P_out);
    parameter q = 14'd12289;
    reg [27:0] s [0:3];
    integer ii;
    always @(posedge clk or posedge rst) begin
      if (rst) begin for (ii=0; ii<4; ii=ii+1) s[ii] <= 0; end
      else begin
        s[0] <= A_in * B_in;
        s[1] <= (s[0][11:0] + (s[0][11:0] << 1)) + 28'd49156 - (s[0] >> 12);
        s[2] <= (s[1][11:0] + (s[1][11:0] << 1)) + 28'd12289 - (s[1] >> 12);
        s[3] <= s[2];
      end
    end
    wire [27:0] r = (s[3] >= 28'd12289) ? (s[3] - 28'd12289) : s[3];
    assign P_out = r[data_width-1:0];
endmodule
