// GENERATED by kred_gen.py for Kyber: q = 3329 = 13*2^8 + 1
// Returns (k^2 * A * B) mod q; fold the factor 169 into the
// twiddle ROM ((k^F)^-1 = 2285).
module modular_mul_kred_kyber #(parameter data_width = 12)(
    input clk, rst,
    input [data_width-1:0] A_in, B_in,
    output wire [data_width-1:0] P_out);
    parameter q = 12'd3329;
    reg [23:0] s [0:3];
    integer ii;
    always @(posedge clk or posedge rst) begin
      if (rst) begin for (ii=0; ii<4; ii=ii+1) s[ii] <= 0; end
      else begin
        s[0] <= A_in * B_in;
        s[1] <= (s[0][7:0] + (s[0][7:0] << 2) + (s[0][7:0] << 3)) + 24'd46606 - (s[0] >> 8);
        s[2] <= (s[1][7:0] + (s[1][7:0] << 2) + (s[1][7:0] << 3)) + 24'd3329 - (s[1] >> 8);
        s[3] <= s[2];
      end
    end
    wire [23:0] r = (s[3] >= 24'd3329) ? (s[3] - 24'd3329) : s[3];
    assign P_out = r[data_width-1:0];
endmodule
