#!/usr/bin/env python3
"""Emit a register-wrapped Fmax harness for a module: all DUT inputs are fed
from an internal shift register and all outputs are registered then XOR-
reduced to one pin, so the only I/O is clk + serial_in + serial_out.  This
isolates the DUT's register-to-register critical path (the meaningful Fmax)
and avoids I/O-placement issues for wide modules.

Usage: wrap.py <design.json> <top>  -> prints wrapper Verilog for `<top>_wrap`.
The DUT is instantiated by named port connection; `clk` connects straight
through, `rst` (if present) is tied 0.
"""
import json
import sys

d = json.load(open(sys.argv[1]))
top = sys.argv[2]
m = d["modules"][top]
ins, outs = [], []
for p, info in m["ports"].items():
    if p in ("clk",):
        continue
    w = len(info["bits"])
    (ins if info["direction"] == "input" else outs).append((p, w))

# rst tied to 0; all other inputs come from the shift register
drive_ins = [(p, w) for p, w in ins if p != "rst"]
in_bits = sum(w for _, w in drive_ins)
out_bits = sum(w for _, w in outs)

conn = ['.clk(clk)']
if any(p == "rst" for p, _ in ins):
    conn.append(".rst(1'b0)")
# slice the input shift register into the driven inputs (MSB-first)
hi = in_bits - 1
for p, w in drive_ins:
    conn.append(".%s(ish[%d:%d])" % (p, hi, hi - w + 1) if w > 1
                else ".%s(ish[%d])" % (p, hi))
    hi -= w
# collect outputs into one concat for registering
owires = " , ".join("o_%s" % p for p, _ in outs)
for p, w in outs:
    conn.append(".%s(o_%s)" % (p, p))

print("// GENERATED by wrap.py — register-wrapped Fmax harness for %s" % top)
print("module %s_wrap (input clk, input serial_in, output serial_out);" % top)
print("  reg [%d:0] ish;" % (in_bits - 1))
print("  always @(posedge clk) ish <= {ish[%d:0], serial_in};" % (in_bits - 2))
for p, w in outs:
    print("  wire [%d:0] o_%s;" % (w - 1, p))
print("  %s dut (%s);" % (top, ", ".join(conn)))
print("  reg [%d:0] osh;" % (out_bits - 1))
print("  always @(posedge clk) osh <= { %s };" % owires)
print("  assign serial_out = ^osh;")
print("endmodule")
